API Get developer details
thupv/rails-example pull request #3
Opened 2018-04-04 02:53 UTC by thupv

# Purpose of PR
Search function

2018-04-04 07:40 UTC, thienhv commented on app/controllers/api/developer_controller.rb
> +      @developer = Developer.includes(:developer_languages, :developer_programmings).find(params[:id])
@thupv 

is `includes(:developer_languages, :developer_programmings)` necessary ?

2018-04-06 02:18 UTC, jp-ryuji requested changes

2018-04-06 02:18 UTC, jp-ryuji commented on spec/requests/api/developer_spec.rb
> +        get '/api/developer/non_exist_id'
Should be `non_existing_id`.
`exist` is a verb.

2018-04-06 02:18 UTC, jp-ryuji commented on spec/requests/api/developer_spec.rb
> +                          email: 'abc2321@gmail.com',
This is a small thing.
But I recommend you to use more meaningless value for email, `abc2321@gmail.com`.
Such as `example`, `test`, `foo` or `bar`, like `foo@example.com`.
Then other developers understand the value doesn't mean anything.

Moreover, you don't need to set email here.
It should be set by factory_bot if you define it.
Can you try this approach?

2018-04-06 02:18 UTC, jp-ryuji commented on spec/controllers/developer_controller_spec.rb
> +require 'rails_helper'
You should remove unused files.

2018-04-06 02:18 UTC, jp-ryuji commented on config/routes.rb
> +  namespace :api do
(REST) api should have versions.

2018-04-06 02:18 UTC, jp-ryuji commented on spec/helpers/developer_helper_spec.rb
> +
You should remove unused files.

2018-04-06 02:18 UTC, jp-ryuji commented on app/helpers/developer_helper.rb
> +module DeveloperHelper
You should remove unused files.

2018-04-06 02:18 UTC, jp-ryuji commented on spec/requests/api/developer_spec.rb
> +              email: @developer.email
The details should be returned.
Not only email.

2018-04-06 02:18 UTC, jp-ryuji commented on spec/requests/api/developer_spec.rb
> +    context 'when the post does not exist' do
post?

2018-04-06 04:55 UTC, jp-ryuji commented on Gemfile
> +gem 'fast_jsonapi'
@thupv 
Good try with `fast_jsonapi`. 
I like the attitude. 👍

2018-04-06 04:55 UTC, jp-ryuji commented on spec/requests/api/developer_spec.rb
> +              email: @developer.email
Sorry.
Forget about the comment.
There's only `email` column.

2018-04-09 07:39 UTC, thupv commented on config/routes.rb
> +  namespace :api do
I added version but github don't recognise, could you check here: https://github.com/thupv/FindDeveloper/pull/1/files

2018-04-09 07:40 UTC, thienhv approved these changes

2018-04-10 07:30 UTC, jp-ryuji approved these changes

2018-04-10 07:32 UTC, merged